// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOuk_XrVVingPCxPMlHPXoF2Fbdf0q9IM',
    appId: '1:304491222885:web:1d49be20e66bb73e68738c',
    messagingSenderId: '304491222885',
    projectId: 'socialapp-74c73',
    authDomain: 'socialapp-74c73.firebaseapp.com',
    storageBucket: 'socialapp-74c73.firebasestorage.app',
    measurementId: 'G-23PMYZ6ESB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcwJH78Qx9aIOnn07iQY-JW-tUrYwnq_o',
    appId: '1:304491222885:android:8111e328d7f880df68738c',
    messagingSenderId: '304491222885',
    projectId: 'socialapp-74c73',
    storageBucket: 'socialapp-74c73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlurnAFi15aNMtpJ6uLgodOqcDlxirdX0',
    appId: '1:304491222885:ios:0aabe61cf1d1a81968738c',
    messagingSenderId: '304491222885',
    projectId: 'socialapp-74c73',
    storageBucket: 'socialapp-74c73.firebasestorage.app',
    iosBundleId: 'com.example.socialapp',
  );
}
